const TEMPLATE_STATUS = {
    DRAFT: "DRAFT",
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    PUBLISHED: "PUBLISHED",
    ARCHIVED: "ARCHIVED",
    DELETED: "DELETED"
};

const TEMPLATE_TYPE = {
    TEMPLATE: "TEMPLATE",
    FOLDER: "FOLDER"
}

const CONTENT_BLOCK_TYPES = {
    HTML: "HTML",
    TEXT: "TEXT",
    BUTTON: "BUTTON",
    IMAGE: "IMAGE",
    DOCUMENT: "DOCUMENT"
}

const MASTER_DATA_TYPES = {
    LANGUAGE: "LANGUAGE",
    TEMPLATE_TYPE: "TEMPLATE_TYPE",
    TEMPLATE_CATEGORY: "TEMPLATE_CATEGORY",
}

const FOLDER_LOCATION = {
    ENTERPRISE_TEMPLATE: "ENTERPRISE_TEMPLATE",
    MOBILYTIX_TEMPLATE: "MOBILYTIX_TEMPLATE"
}

const MAX_COUNTS = {
    SUB_FOLDERS: 10
}

const CONTENT_BLOCK_TAGS = {
    HEADER: "HEADER",
    BODY: "BODY",
    FOOTER: "FOOTER",
    SHORTEN: "SHORTEN"
}

const WHATSAPP_TEMPLATE_BUTTON_TYPE = {
    QUICK_REPLY: "QUICK_REPLY",
    CALL_TO_ACTION: "CALL_TO_ACTION"
}

module.exports = {
    TEMPLATE_STATUS,
    TEMPLATE_TYPE,
    CONTENT_BLOCK_TYPES,
    MASTER_DATA_TYPES,
    FOLDER_LOCATION,
    MAX_COUNTS,
    CONTENT_BLOCK_TAGS,
    WHATSAPP_TEMPLATE_BUTTON_TYPE
}